openapi: 3.0.0
paths:
  /v1/cdi:
    get:
      operationId: CDIController_cdiApp
      parameters: []
      responses:
        '200':
          description: 'OK'
        '400':
          description: 'BAD REQUEST'
info:
  title: CDI Mensal
  description: Operação de taxa de juros entre bancos dos últimos 12 meses
  version: '1.0'
  contact: {}
tags:
  - name: cdi
    description: ''
servers:  
- url: https://victoria-belo.github.io/
components:
  schemas: {}
