openapi: 3.0.0
paths:
  /v1/cdi:
    get:
      operationId: CDIController_cdiApp
      parameters: []
      responses:
        '200':
          description: The request has been successfully.
        '400':
          description: Bad Request.
      tags:
        - cdi
info:
  title: Certificado de Depósito Interbancário Mensal
  description: Taxa de juros entre bancos
  version: '1.0'
  contact: {}
tags:
  - name: cdi
    description: ''
servers: []
components:
  schemas: {}
