openapi: 3.0.0

paths:
  /v1/cdi:
  servers:  
    get:
      operationId: CDIController_cdiApp
      parameters: []
      responses:
        '200':
          description: The request has been successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
              examples:
                GET v1/cdi:
                  value: |-
                    [
                       
                        {
                            "data": "01/02/2023",
                            "valor": "0.92"
                        },
                        {
                            "data": "01/01/2023",
                            "valor": "1.12"
                        },
                        {
                            "data": "01/12/2022",
                            "valor": "1.12"
                        }
                      
                    ]
        '400':
          description: Bad Request
        '404':
          description: Not Found
      
      tags:
        - cdi
info:
  title: Certificado de Depósito Interbancário Mensal
  description: Taxa de juros entre bancos
  version: '1.0'
  contact: {}
tags:
  - name: cdi
    description: ''
servers: []
components:
  schemas: {}
